### ISSUE TITLE
Source §3: suspected memory leak

### ISSUE THREAD

**Issue by salty-flower** [source-academy/js-slang#1179] opened 2021-12-04 01:10 UTC
_Coppied from [Piazza thread](https://piazza.com/class/krvh5l6ipib380?cid=419)_: repeated "Runs" of Source programs seem to accumulate uncollectable memory.

Environment: Chrome Version 94.0.4606.81 (Official Build) (64-bit) on Windows 10.

**Comment by martin-henz** [comment] 2021-12-04 06:14
We need to have a (hopefully minimal) example, to get to the bottom of this: A Source program that exhibits the memory leak. We need to find out if this has anything to do with pix-n-flix. (I suspect it does.)

**Comment by salty-flower** [comment] 2021-12-04 06:37
One sample program:

_this is NOT the program from the OP._
On my machine (Win10 21H1), the program executes slower and slower, and memory cost grows from 300~400 MB to 1800 MB (MS Edge) and 700 MB (Chrome), at which stage the browser becomes not responsive at all.

`const array_to_stream = a => build_stream(i => a[i], array_length(a));

function stream_to_filter(s) {
    let m = s;
    let this_frame = undefined;
    let last_frame = undefined;
    
    return (src, dest) => {
        if (!is_null(stream_tail(m))) {
            // next frame is valid
            this_frame = head(m);
            
            // next next frame is invalid, then store next frame
            if (is_null(stream_tail(stream_tail(m)))) {
                last_frame = head(stream_tail(m));
            }
            
            // put it on
            for (let i = 0; i < HEIGHT; i = i + 1) {
                for (let j = 0; j < WIDTH; j = j + 1) {
                   dest[i][j][0] = this_frame[i][j][0];
                   dest[i][j][1] = this_frame[i][j][1];
                   dest[i][j][2] = this_frame[i][j][2];
                   dest[i][j][3] = this_frame[i][j][3];
                }
            }
            
            // switch to next frame
            m = stream_tail(m);
        } else {
            // next frame is invalid
            // go back to first frame
            m = s;
        }
    };
}

install_filter(stream_to_filter(array_to_stream(anomaly_data)));
set_dimensions(WIDTH, HEIGHT);
start();`

**Comment by martin-henz** [comment] 2022-01-23 23:13
Does anybody remember what's the conclusion on this? Do we know what causes the problem?

**Comment by martin-henz** [comment] 2023-07-19 02:36
Here is a link to the example above:
https://share.sourceacademy.org/xx9tk

**Comment by martin-henz** [comment] 2023-07-19 02:36
And the program text here:
```
import {
    install_filter, set_dimensions, start
} from 'pix_n_flix';

const anomaly_data = [];

const HEIGHT = 300;
const WIDTH = 400;

{
    const red = 0;
    const green = 1;
    const blue = 2;
    const number_of_frames = 20;
    const black_pixel = [0, 0, 0, 255];
    const red_pixel = [255, 0, 0, 255];
    const white_pixel = [255, 255, 255, 255];
    const yellow_pixel = [255, 255, 235, 255];
    const black_rows = [];
    for (let i = 0; i < HEIGHT; i = i + 1) {
        let black_row = [];
        for (let j = 0; j < WIDTH; j = j + 1) {
            black_row[j] = black_pixel;
            if (math_random() < 0.01) {
                const brite = math_floor(256 * (0.25 + math_random() * 0.75)); 
                black_row[j] = [brite, brite, brite, 255];
                //black_row[j] = white_pixel;
            } else {}
        }
        black_rows[i] = black_row;
    }
    // anomaly_data is an array of images
    const square_size = 10;
    const inner_square_size = 4;
    for (let f = 0; f < number_of_frames; f = f + 1) {
        const g = f < number_of_frames / 2 ? f : number_of_frames - f;
        if (g !== f) { 
            anomaly_data[f] = anomaly_data[g];
        } else {
            anomaly_data[f] = []; 
            for (let i = 0; i < HEIGHT; i = i + 1) {
                function difference_from_half(x, t) {
                    return math_abs(t / 2 - x);
                }
                if (difference_from_half(i, HEIGHT) < square_size) {
                    anomaly_data[f][i] = [];
                    for (let j = 0; j < WIDTH; j = j + 1) {
                        if (difference_from_half(j + 2 * g, WIDTH) < square_size) {
                            const d = math_hypot(difference_from_half(i, HEIGHT),
                                                 difference_from_half(j + 2 * g, WIDTH));
                            if (d < square_size) {
                                if (d < inner_square_size) {
                                    if (d <= 2 && f === 7) {
                                        anomaly_data[f][i][j] = yellow_pixel;
                                    } else {
                                        anomaly_data[f][i][j] = white_pixel;
                                    }
                                } else {
                                    anomaly_data[f][i][j] = red_pixel;
                                }
                            } else {
                                anomaly_data[f][i][j] = black_rows[i][j];
                            }
                        } else {
                             anomaly_data[f][i][j] = black_rows[i][j];
                        }
                    }
                } else {
                    anomaly_data[f][i] = black_rows[i];
                }
            }
        }
    }
}



const array_to_stream = a => build_stream(i => a[i], array_length(a));

function stream_to_filter(s) {
    let m = s;
    let this_frame = undefined;
    let last_frame = undefined;
    
    return (src, dest) => {
        if (!is_null(stream_tail(m))) {
            // next frame is valid
            this_frame = head(m);
            
            // next next frame is invalid, then store next frame
            if (is_null(stream_tail(stream_tail(m)))) {
                last_frame = head(stream_tail(m));
            }
            
            // put it on
            for (let i = 0; i < HEIGHT; i = i + 1) {
                for (let j = 0; j < WIDTH; j = j + 1) {
                   dest[i][j][0] = this_frame[i][j][0];
                   dest[i][j][1] = this_frame[i][j][1];
                   dest[i][j][2] = this_frame[i][j][2];
                   dest[i][j][3] = this_frame[i][j][3];
                }
            }
            
            // switch to next frame
            m = stream_tail(m);
        } else {
            // next frame is invalid
            // go back to first frame
            m = s;
        }
    };
}

install_filter(stream_to_filter(array_to_stream(anomaly_data)));
set_dimensions(WIDTH, HEIGHT);
start();
```

**Comment by martin-henz** [comment] 2023-07-19 02:37
Can't reproduce the problem, but need to test on different platforms.

**Comment by martin-henz** [comment] 2024-03-30 09:12
This is fine in firefox and chrome. Can someone try on Windows? (I'm running on mac.)

**Comment by RichDom2185** [comment] 2024-03-31 04:15
> This is fine in firefox and chrome. Can someone try on Windows? (I'm running on mac.)

Can I ping @leeyi45 to test if you're free? This issue is quite old so if you can't reproduce it we can just close the issue.

**Comment by leeyi45** [comment] 2024-03-31 04:19
I don't have access to my windows machine right now unfortunately

**Comment by Cloud7050** [comment] 2024-04-04 17:14
I am the OP from Piazza and watched this GitHub issue back then. I am pleased to say I can no longer reproduce this on Windows (11 now) Chrome, even using my old snippets in the original mission environment:

![image](https://github.com/source-academy/js-slang/assets/44526554/09182f88-c58a-41d6-9fea-e6fba94a9892)

---

Piazza link to response: https://piazza.com/class/krvh5l6ipib380/post/419_f2
Recording of old issue: https://youtu.be/QczuClom0j0

**Closed by Cloud7050** 2024-04-04 17:14 UTC
Labels: Bug, minor
