### ISSUE TITLE
It failed to run "npm link" on wsl2 of windows

### ISSUE THREAD

**Issue by AbstProcDo** [source-academy/js-slang#818] opened 2020-12-06 06:12 UTC
After running "npm link" , it report error:

```
29604 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
29605 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
29606 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
29606 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
29606 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
29606 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
29607 warn xmlhttprequest-ts@1.0.1 requires a peer of @angular/common@>= 5.0.0 but none is installed. You must install peer dependencies yourself.
29608 warn xmlhttprequest-ts@1.0.1 requires a peer of @angular/core@>= 5.0.0 but none is installed. You must install peer dependencies yourself.
29609 verbose stack Error: gl@4.9.0 install: `prebuild-install || node-gyp rebuild`
29609 verbose stack Exit status 1
29609 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
29609 verbose stack     at EventEmitter.emit (events.js:198:13)
29609 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
29609 verbose stack     at ChildProcess.emit (events.js:198:13)
29609 verbose stack     at maybeClose (internal/child_process.js:982:16)
29609 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
29610 verbose pkgid gl@4.9.0
29611 verbose cwd /mnt/c/Users/gaowei/Public/Master-JavaScript-Instantly/js-slang/dist
29612 verbose Linux 4.19.104-microsoft-standard
29613 verbose argv "/usr/bin/node" "/usr/bin/npm" "link"
29614 verbose node v10.19.0
29615 verbose npm  v6.14.4
29616 error code ELIFECYCLE
29617 error errno 1
29618 error gl@4.9.0 install: `prebuild-install || node-gyp rebuild`
29618 error Exit status 1
29619 error Failed at the gl@4.9.0 install script.
29619 error This is probably not a problem with npm. There is likely additional logging output above.
29620 verbose exit [ 1, true ]
```

**Comment by Anonymxtrix** [comment] 2021-02-16 01:46
Lines 29618 to 29620 looks familiar to me. It was an issue with my node version (I was using latest at v15.8.0). It was fixed after I downgraded to the LTS version which is v14.15.5. 

```
$ yarn install -g n
$ n lts
```

**Comment by martin-henz** [comment] 2021-02-16 02:11
Hmm, wouldn't call that a "fix". If LTS version is bumped, this will likely resurface. Any suggestion how to fix this permanently?

**Comment by Anonymxtrix** [comment] 2021-02-16 04:19
It appears that there may be an issue with node-gyp which is a dependency in js-slang. The issue is discussed further in detail [here](https://github.com/nodejs/node-gyp/issues/2113). 

A solution suggested is to run the following commands to reinstall node_modules and node-gyp. 

```
$ yarn add -g node-gyp
$ export npm_config_node_gyp=/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
$ rm -rf node_modules(if already there)
$ yarn install
```

**Comment by martin-henz** [comment] 2021-02-16 05:25
So the "solution" is to make an env variable point to a particular file? We'd need to make that part of test setup? Hmm, what do we need node-gyp for?

**Comment by martin-henz** [comment] 2024-03-30 09:04
Quite obscure issue. Should we close it?

**Comment by RichDom2185** [comment] 2024-03-31 03:57
Seems like we can close this. NodeJS, node-gyp, js-slang, and gl have all been bumped since the last update and we see no such issues in recent time. If someone can reproduce this again with their system feel free to file a new/reopen this issue.

**Closed by RichDom2185** 2024-03-31 03:57 UTC
Labels: minor, dependencies
