### ISSUE TITLE
Anonymous arrow function expressions are represented as DummyClass 

### ISSUE THREAD

**Issue by remo5000** [source-academy/js-slang#19] opened 2018-07-17 07:02 UTC
Arrow functions on their own are represented fine, but not when nested in something else.

- Evaluate `pair((x) => x, 4);`
- Expected: `[x => x, 4]`
- Actual: `[function DummyClass() {
	[implementation hidden]
    }, 4]`

**Comment by openorclose** [comment] 2018-11-25 11:42
This should be closed in favour of #88 as they are caused by the same bug, namely improper passing of Source-defined functions into native Javascript functions.

**Comment by martin-henz** [comment] 2018-11-25 11:47
OK, noted.

**Closed by martin-henz** 2018-11-25 11:47 UTC
Labels: Bug, minor
