### ISSUE TITLE
Disallow programs where function declarations do not appear at the top of their block scope

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/js-slang#40] opened 2018-08-26 15:04 UTC
```js
const f = g();

function g() {
    return 1;
}
```

Throws reference error in source, but should work according to ES6.

**Comment by martin-henz** [comment] 2018-09-20 10:49
Yes, this will require quite some effort. There are two cases:

(1) Local functions

It's tempting to restrict Source such that all local functions need to appear first within a function body. This will require a small note in the Source docs, and a simple check during interpretation. A nice error message will remind the students to do the right thing:
"local functions must appear before any other statements in the function body"

(2) Toplevel

Here, I think hoisting is both feasible and desirable, and should be implemented as a preprocessing step.

To be discussed are weird cases like this (at toplevel):

f(1);
if (true) { function f(x) { } }

Allowed in Source 2019 or not? Hoisted in Source 2019 or not?

**Comment by openorclose** [comment] 2018-09-20 12:55
@martin-henz Up till ES5 the example code was invalid per the specs as functions are not allowed inside a block statement, but browsers being browsers ignored this and each had a different way of interpreting the code.  

Since ES2015 however, functions are now block scoped and so the example code would also be invalid but because the function will not be accessible outside the block scope created by ```if```. To be clear, the function would still be hoisted, but only to the top of the ```if``` statement and not outside of it.

**Comment by ningyuansg** [comment] 2018-09-30 15:59
Sorry, I don't quite understand why the example program would not run. Each function is defined before being called, aren't they?

**Comment by martin-henz** [comment] 2018-09-30 23:00
> Sorry, I don't quite understand why the example program would not run. Each function is defined before being called, aren't they?

We would simply reject this program, because the function declaration for f2 appears after a statement that is not a function declaration.

The reasoning here is to disallow programs where the "hoisting" of a function declaration would happen in ES. This way, we can remain a sublanguage of ES and claim that all legal Source programs are legal ES programs and produce the same result.

(We are deviating from ES in the result of loops, which we declare a "trivial" difference, if anyone asks.)

-martin

**Comment by thomastanck** [comment] 2018-11-16 07:35
If we're keeping this, then the issue should be renamed to something like: "2019: Disallow programs where function declarations do not appear at the top of their block scope."

Or a new issue should be made.

**Comment by thomastanck** [comment] 2018-12-07 17:10
Closing as this is now a duplicate of #136

**Closed by thomastanck** 2018-12-07 17:10 UTC
Labels: Enhancement, minor
