### ISSUE TITLE
CSE Machine: Evaluation of block statements should be split into two steps

### ISSUE THREAD

**Issue by NhatMinh0208** [source-academy/js-slang#1537] opened 2024-02-15 13:24 UTC
Currently, when evaluating block statements, the CSE machine creates the environment for the block _and_ unpacks the block statement in the same step, as seen when running [this](https://share.sourceacademy.org/dicgu) program.

This is confusing to students. We want to split evaluation of block statements into two steps:

1. Create the environment and the necessary instructions.
2. Unpacks the block statement and place its content into the Control stack.

**Comment by martin-henz** [comment] 2024-02-15 14:10
I agree this is an issue that should be fixed.

**Comment by martin-henz** [comment] 2024-02-20 07:55
The steps are still combined.

**Comment by RichDom2185** [comment] 2024-02-20 08:04
> The steps are still combined.

I can't reproduce it. It correctly splits into two steps in the example program at the top of the issue. Perhaps your frontend isn't updated?

**Comment by martin-henz** [comment] 2024-02-20 08:20
> > The steps are still combined.
> 
> I can't reproduce it. It correctly splits into two steps in the example program at the top of the issue. Perhaps your frontend isn't updated?

I currently get this:

<img width="886" alt="Screenshot 2024-02-20 at 4 19 38 PM" src="https://github.com/source-academy/js-slang/assets/30220768/f6093e4f-e7fd-48d4-9555-aced04c6da32">

and

<img width="886" alt="Screenshot 2024-02-20 at 4 19 49 PM" src="https://github.com/source-academy/js-slang/assets/30220768/66d32eb3-9cf9-44e2-825c-780f175a1462">

**Comment by martin-henz** [comment] 2024-02-20 08:21
We want two steps: (1) removal of the block (and creation of the frame) and (2) splitting the sequence into its components

**Comment by martin-henz** [comment] 2024-02-20 09:41
The step from 4 to 5 is too big. It should be:
4 to 5a: make the frame, remove the { ... } from the block, but keep the sequence intact (don't split the sequence up into its components
5a to 5b: split the sequence into its two components, as in the last picture above.

**Comment by RichDom2185** [comment] 2024-02-20 10:02
> The step from 4 to 5 is too big. It should be:
> 4 to 5a: make the frame, remove the { ... } from the block, but keep the sequence intact (don't split the sequence up into its components
> 5a to 5b: split the sequence into its two components, as in the last picture above.

3 to 4 is already doing what you mentioned as "4 to 5a" (see the frame creation and the reset env instruction).

4 to 5 is doing "5a to 5b".

This seems to be a frontend issue. It doesn't know how to display a raw block statement (no braces) so it defaults to displaying it as a block statement (with the braces) instead, causing the illusion I mentioned

**Closed** 2024-02-20 15:33 UTC
Labels: Enhancement, handled in PR
