### ISSUE TITLE
Missing commits of updating of versions: 1.0.21, 1.0.22, 1.0.23

### ISSUE THREAD

**Issue by RichDom2185** [source-academy/js-slang#1414] opened 2023-05-02 20:52 UTC
Seems like the past few deployments to NPM (`1.0.21`, `1.0.22`, `1.0.23`) were not accompanied with the usual "Bump version" commit message. This is not good (I actually think it's quite critical considering we published these releases) as the "release notes"/changes between these three versions are thus unknown, despite being supposedly "patch" releases.

I can foresee this as a huge risk if we continue to deploy manually, and if more people start using our package.

I think we should set up a deploy to NPM GitHub action using a trigger workflow dispatch available to admins only to publish the latest version to NPM and add the version bump to `package.json` automatically. Perhaps we can also automatically generate a corresponding GitHub release; seems like the last one was `v0.3.6· back in 2020.

**Comment by RichDom2185** [comment] 2023-05-02 21:13
Some possible resolutions:

* Force-push to include the commit messages for the past 3 versions (extreme, very messy, especially if forks have been since updated)
* Just git tag the commits instead (knowing that the version number in package.json would be mismatched)
* Remove the three versions from the NPM registry and pray that no one in the whole world used any of these versions (although it has the minor consequence that anyone who looks through our commit history in the frontend will "see" these missing versions
* Just live with it, acknowledge the mistake, **ensure this can never happen again**, and move on

@martin-henz @shenyih0ng @chownces @ianyong I'm curious to know your thoughts on this. I don't see any outcome without side-effects. We'll have to weight the pros and cons of each option.

**Comment by ianyong** [comment] 2023-05-03 03:56
> I think we should set up a deploy to NPM GitHub action using a trigger workflow dispatch available to admins only to publish the latest version to NPM and add the version bump to `package.json` automatically. Perhaps we can also automatically generate a corresponding GitHub release; seems like the last one was `v0.3.6· back in 2020.

This would be nice to have! If we're writing the action ourselves, note that the `yarn version` command will [automatically add a git tag](https://classic.yarnpkg.com/lang/en/docs/cli/version/#toc-git-tags) which we can then push (and base the release off it).

> I'm curious to know your thoughts on this. I don't see any outcome without side-effects. We'll have to weight the pros and cons of each option.

Not in favour of rewriting history on the `master` branch or removing the versions from the npm registry since these should ideally be immutable (especially if doing so results in the same version number referring to more than 1 release throughout its entire lifetime). Tagging the commits is fine I guess, but we also have the problem that the version in `package.json` is not up to date. That's something we definitely should fix.

Taking a look at the commit history as well as npm versions, it seems that v1.0.21, v1.0.22 and v1.0.23 were created in quick succession due to the new changes pulled in not working. Specifically, #1405 and #1404 fixed various issues. The GitHub Action proposed will solve the issue of misaligned versions, but I feel that the real problem here is the lack of testing, both in terms of actually running the frontend with js-slang locally (which would have very quickly made the bugs addressed by these PRs noticeable since py-slang couldn't even be run!) as well as the lack of good test cases (both of these PRs did not add test cases to catch the regressions they fixed and the existing test cases did not catch these issues).

**Comment by RichDom2185** [comment] 2023-05-18 08:47
Running the following:

```zsh
npm view js-slang time --json
```

Gives us the following result:

```jsonc
{
  "0.1.0": "2018-07-10T05:30:14.142Z",
  // ...
  "1.0.14": "2023-02-27T00:13:47.774Z",
  "1.0.15": "2023-03-10T07:44:14.595Z",
  "1.0.16": "2023-03-23T02:58:06.652Z",
  "1.0.17": "2023-03-28T10:42:43.805Z",
  "1.0.18": "2023-04-02T23:59:24.740Z",
  "1.0.19": "2023-04-03T10:20:46.547Z",
  "1.0.20": "2023-04-04T00:56:40.916Z",
  "1.0.21": "2023-04-13T06:51:01.789Z",
  "1.0.22": "2023-04-14T05:18:30.991Z",
  "1.0.23": "2023-04-15T03:01:28.347Z"
}
```

Taking a look at the commit history, it seems that versions `1.0.22` and `1.0.23` are both created between commits d04dd404d0552b620d8c52eb5c4b066234deb21e and 6f2da59574509d599ee1aa6fe37044dad19310b2.

**Comment by RichDom2185** [comment] 2023-05-18 08:48
I'm in the process of tagging the commits at the moment, so far I have the following:

| Tag | Commit Hash |
|:-:|:-:|
|`v1.0.21`|579688590d2267b651d5273355ba6ed36bea530f|
|`v1.0.22`|???|
|`v1.0.23`|???|

**Comment by RichDom2185** [comment] 2023-05-18 08:53
@martin-henz Hi Prof, do you recall which commits correspond to the respective versions?

**Comment by RichDom2185** [comment] 2023-05-18 09:09
> @martin-henz Hi Prof, do you recall which commits correspond to the respective versions?

@Fidget-Spinner @s-kybound as authors of the commits, could you help cross-check the above table as well?

**Comment by s-kybound** [comment] 2023-05-18 10:21
> > @martin-henz Hi Prof, do you recall which commits correspond to the respective versions?
> 
> @Fidget-Spinner @s-kybound as authors of the commits, could you help cross-check the above table as well? If all looks good, I'll go ahead and push the tags.

Hi, by running `diff -r` between versions 1.0.20, 1.0.21, 1.0.22 and 1.0.23, the changes are as follows:

(I'm unable to provide an exhaustive list of changes (commits) between versions, I was only looking at the code changed by the Interactive Environment Visualiser, py-slang and scm-slang)

1.0.21: 
- Interactive Environment Visualiser added (579688590d2267b651d5273355ba6ed36bea530f)
- py-slang added (c4ee470f18cbfb07dc8fdac88147d37aebc6421e)
- scm-slang added (c9c51958819cc210e6857a5facbcc69849f1bdcc)

1.0.22:
- py-slang fixed (bfdb30dd2a99622f6ada68af0721cf5c706548eb)
- scm-slang fixed (d04dd404d0552b620d8c52eb5c4b066234deb21e)

1.0.23:
As for the difference between versions 1.0.22 and 1.0.23, the output from `diff` indicates that the only difference between the two versions is a bump in version in the package.json from 1.0.22 to 1.0.23.

**Comment by Fidget-Spinner** [comment] 2023-05-18 11:08
In general I think Ky's approach to finding the commits may be more accurate.

**Comment by RichDom2185** [comment] 2023-05-18 11:17
> Hi, by running `diff -r` between versions 1.0.20, 1.0.21, 1.0.22 and 1.0.23, the changes are as follows:

I was trying to do something like this but wasn't sure how, did you just install each of the versions into their own directory and compared two at a time?

> Regarding the difference between versions 1.0.22 and 1.0.23, the output from `diff -r` indicates that the only difference between the two versions is a bump in version in the package.json from 1.0.22 to 1.0.23.

That would agree with the output `npm view js-slang time --json` – the timestamp for `1.0.22` is after both bfdb30dd2a99622f6ada68af0721cf5c706548eb and d04dd404d0552b620d8c52eb5c4b066234deb21e, leaving no commits between the timestamps of `1.0.22` and `1.0.23` as mentioned in https://github.com/source-academy/js-slang/issues/1414#issuecomment-1552739249; I simply was still under the assumption that there must've been at least 1 commit between each patch version.

But since diff agrees with the timestamps, I guess we can simply tag both `v1.0.22` and `v1.0.23` to d04dd404d0552b620d8c52eb5c4b066234deb21e.

**Comment by s-kybound** [comment] 2023-05-18 11:36
> > Hi, by running `diff -r` between versions 1.0.20, 1.0.21, 1.0.22 and 1.0.23, the changes are as follows:
> 
> I was trying to do something like this but wasn't sure how, did you just install each of the versions into their own directory and compared two at a time?
> 
> > Regarding the difference between versions 1.0.22 and 1.0.23, the output from `diff -r` indicates that the only difference between the two versions is a bump in version in the package.json from 1.0.22 to 1.0.23.
> 
> That would agree with the output `npm view js-slang time --json` – the timestamp for `1.0.22` is after both bfdb30dd2a99622f6ada68af0721cf5c706548eb and d04dd404d0552b620d8c52eb5c4b066234deb21e, leaving no commits between the timestamps of `1.0.22` and `1.0.23` as mentioned in https://github.com/source-academy/js-slang/issues/1414#issuecomment-1552739249; I simply was still under the assumption that there must've been at least 1 commit between each patch version.
> 
> But since diff agrees with the timestamps, I guess we can simply tag both `v1.0.22` and `v1.0.23` to d04dd404d0552b620d8c52eb5c4b066234deb21e.

Yep, that's how I did it

**Comment by RichDom2185** [comment] 2023-05-18 11:50
I've pushed the tags as follows:

| Tag | Commit Hash |
|:-:|:-:|
|[v1.0.21](https://github.com/source-academy/js-slang/releases/tag/v1.0.21)|579688590d2267b651d5273355ba6ed36bea530f|
|[v1.0.22](https://github.com/source-academy/js-slang/releases/tag/v1.0.22)|d04dd404d0552b620d8c52eb5c4b066234deb21e|
|[v1.0.23](https://github.com/source-academy/js-slang/releases/tag/v1.0.23)|d04dd404d0552b620d8c52eb5c4b066234deb21e|

**Comment by Fidget-Spinner** [comment] 2023-05-18 11:54
Thanks for resolving this!

**Closed** 2023-05-23 14:14 UTC
Labels: critical
